#! /bin/sh

bspc config border_width        2
bspc config window_gap         12
bspc config top_padding        15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true

bspc monitor -d www code irc IV V VI VII VIII IX X

bspc rule -a firefox desktop=^1
bspc rule -a xterm floating=on # I only use xterm for clusterssh, so float it
bspc rule -a clusterssh floating=on
# bspc rule -a Gimp desktop=^8 follow=on floating=on
# bspc rule -a Chromium desktop=^2
# bspc rule -a mplayer2 floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Set the cursor to the normal arrow shape
xsetroot -cursor_name left_ptr 

export PATH="$HOME/.config/bspwm/panel:$PATH"
panel &
