general {
  lock_cmd = pidof hyprlock || hyprlock
  before_sleep_cmd = loginctl lock-session
}

listener {
  timeout = 300 # Lock the screen after 5 minutes
  on-timeout = loginctl lock-session
}

listener {
  timeout = 420 # Turn off the screen after 7 minutes
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}
