function awsvars --description 'Print out AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN'
	echo "AWS_ACCESS_KEY_ID =" $AWS_ACCESS_KEY_ID
	echo "AWS_SECRET_ACCESS_KEY =" $AWS_SECRET_ACCESS_KEY
	echo "AWS_SESSION_TOKEN =" $AWS_SESSION_TOKEN
end
